/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Restaurante.views;

import com.Restaurante.models.Restaurante;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Usuario
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private Restaurante restaurante;    
    /**
     * Creates new form VentanaPrincipal2
     */
    public VentanaPrincipal(Restaurante restaurante) {
        initComponents();
        this.setLocationRelativeTo(null);
        try{
            this.setIconImage(new ImageIcon(getClass().getResource("com.Restaurante.imagen.restaurante.png")).getImage());
        }catch(Exception e){
            
        }
        
        this.restaurante = restaurante;
        this.LblNombreRestaurante.setText(this.restaurante.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LblNombreRestaurante = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnAgregarPlatoInternacional = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnAgregarPlatoNacionaloTipico = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnMostrarMenu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnMostrarVenta = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        jPanel2.setBackground(new java.awt.Color(51, 153, 0));

        LblNombreRestaurante.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        LblNombreRestaurante.setForeground(new java.awt.Color(0, 0, 0));
        LblNombreRestaurante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblNombreRestaurante.setText("Nombre de la tienda");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addComponent(LblNombreRestaurante)
                .addGap(190, 190, 190))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(LblNombreRestaurante)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 100));

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregarPlatoInternacional.setBackground(new java.awt.Color(255, 51, 51));
        btnAgregarPlatoInternacional.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarPlatoInternacionalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarPlatoInternacionalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarPlatoInternacionalMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Restaurante/imagen/comida  internacional.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Internacionales");

        javax.swing.GroupLayout btnAgregarPlatoInternacionalLayout = new javax.swing.GroupLayout(btnAgregarPlatoInternacional);
        btnAgregarPlatoInternacional.setLayout(btnAgregarPlatoInternacionalLayout);
        btnAgregarPlatoInternacionalLayout.setHorizontalGroup(
            btnAgregarPlatoInternacionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAgregarPlatoInternacionalLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(btnAgregarPlatoInternacionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(btnAgregarPlatoInternacionalLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)))
                .addGap(16, 16, 16))
        );
        btnAgregarPlatoInternacionalLayout.setVerticalGroup(
            btnAgregarPlatoInternacionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarPlatoInternacionalLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jPanel3.add(btnAgregarPlatoInternacional, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        btnAgregarPlatoNacionaloTipico.setBackground(new java.awt.Color(255, 51, 51));
        btnAgregarPlatoNacionaloTipico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarPlatoNacionaloTipicoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarPlatoNacionaloTipicoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarPlatoNacionaloTipicoMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Restaurante/imagen/comida nacional o tipica.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nacionales o Tipicos");

        javax.swing.GroupLayout btnAgregarPlatoNacionaloTipicoLayout = new javax.swing.GroupLayout(btnAgregarPlatoNacionaloTipico);
        btnAgregarPlatoNacionaloTipico.setLayout(btnAgregarPlatoNacionaloTipicoLayout);
        btnAgregarPlatoNacionaloTipicoLayout.setHorizontalGroup(
            btnAgregarPlatoNacionaloTipicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarPlatoNacionaloTipicoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(btnAgregarPlatoNacionaloTipicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAgregarPlatoNacionaloTipicoLayout.setVerticalGroup(
            btnAgregarPlatoNacionaloTipicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarPlatoNacionaloTipicoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btnAgregarPlatoNacionaloTipicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAgregarPlatoNacionaloTipicoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())))
        );

        jPanel3.add(btnAgregarPlatoNacionaloTipico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        btnMostrarMenu.setBackground(new java.awt.Color(255, 51, 51));
        btnMostrarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMostrarMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMostrarMenuMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Restaurante/imagen/mostrar menu.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Menu");

        javax.swing.GroupLayout btnMostrarMenuLayout = new javax.swing.GroupLayout(btnMostrarMenu);
        btnMostrarMenu.setLayout(btnMostrarMenuLayout);
        btnMostrarMenuLayout.setHorizontalGroup(
            btnMostrarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMostrarMenuLayout.createSequentialGroup()
                .addGroup(btnMostrarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnMostrarMenuLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3))
                    .addGroup(btnMostrarMenuLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel8)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        btnMostrarMenuLayout.setVerticalGroup(
            btnMostrarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMostrarMenuLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        jPanel3.add(btnMostrarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 150, 160));

        btnMostrarVenta.setBackground(new java.awt.Color(255, 51, 51));
        btnMostrarVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMostrarVentaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMostrarVentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMostrarVentaMouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Restaurante/imagen/venta.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("MOSTRAR VENTA");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Venta");

        javax.swing.GroupLayout btnMostrarVentaLayout = new javax.swing.GroupLayout(btnMostrarVenta);
        btnMostrarVenta.setLayout(btnMostrarVentaLayout);
        btnMostrarVentaLayout.setHorizontalGroup(
            btnMostrarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMostrarVentaLayout.createSequentialGroup()
                .addGroup(btnMostrarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnMostrarVentaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4))
                    .addGroup(btnMostrarVentaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(btnMostrarVentaLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel11)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        btnMostrarVentaLayout.setVerticalGroup(
            btnMostrarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMostrarVentaLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(13, 13, 13)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel3.add(btnMostrarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("AGREGAR PLATOS");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("MOSTRAR MENU");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 700, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPlatoNacionaloTipicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarPlatoNacionaloTipicoMouseClicked
        System.out.println("Agregar Plato nacional o Tipico");
    }//GEN-LAST:event_btnAgregarPlatoNacionaloTipicoMouseClicked

    private void btnAgregarPlatoNacionaloTipicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarPlatoNacionaloTipicoMouseEntered
       this.mouseEntered(btnAgregarPlatoNacionaloTipico);
    }//GEN-LAST:event_btnAgregarPlatoNacionaloTipicoMouseEntered

    private void btnAgregarPlatoNacionaloTipicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarPlatoNacionaloTipicoMouseExited
        this.mouseEcited(btnAgregarPlatoNacionaloTipico);
    }//GEN-LAST:event_btnAgregarPlatoNacionaloTipicoMouseExited

    private void btnAgregarPlatoInternacionalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarPlatoInternacionalMouseClicked
        System.out.println("Agregar Plato Internacional");
    }//GEN-LAST:event_btnAgregarPlatoInternacionalMouseClicked

    private void btnAgregarPlatoInternacionalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarPlatoInternacionalMouseEntered
       this.mouseEntered(btnAgregarPlatoInternacional);
    }//GEN-LAST:event_btnAgregarPlatoInternacionalMouseEntered

    private void btnAgregarPlatoInternacionalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarPlatoInternacionalMouseExited
       this.mouseEcited(btnAgregarPlatoInternacional);
    }//GEN-LAST:event_btnAgregarPlatoInternacionalMouseExited

    private void btnMostrarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarMenuMouseClicked
        System.out.println("Mostrar Menu");
    }//GEN-LAST:event_btnMostrarMenuMouseClicked

    private void btnMostrarMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarMenuMouseEntered
       this.mouseEntered(btnMostrarMenu);
    }//GEN-LAST:event_btnMostrarMenuMouseEntered

    private void btnMostrarMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarMenuMouseExited
        this.mouseEcited(btnMostrarMenu);
    }//GEN-LAST:event_btnMostrarMenuMouseExited

    private void btnMostrarVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarVentaMouseClicked
        System.out.println("Mostrar Venta");
    }//GEN-LAST:event_btnMostrarVentaMouseClicked

    private void btnMostrarVentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarVentaMouseEntered
        this.mouseEntered(btnMostrarVenta);
    }//GEN-LAST:event_btnMostrarVentaMouseEntered

    private void btnMostrarVentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarVentaMouseExited
       this.mouseEcited(btnMostrarVenta);
    }//GEN-LAST:event_btnMostrarVentaMouseExited

    private void mouseEntered(JPanel panel){
        panel.setBackground(new Color(251,150,150));
    }
    private void mouseEcited(JPanel panel){
         panel.setBackground(new Color(255,51,51));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblNombreRestaurante;
    private javax.swing.JPanel btnAgregarPlatoInternacional;
    private javax.swing.JPanel btnAgregarPlatoNacionaloTipico;
    private javax.swing.JPanel btnMostrarMenu;
    private javax.swing.JPanel btnMostrarVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
